-- CoverGrail beta-readiness data: feedback and privacy-preserving product events.

begin;

create table if not exists public.beta_feedback (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  category text not null
    check (category in ('bug', 'idea', 'grading', 'other')),
  rating integer
    check (rating is null or (rating >= 1 and rating <= 5)),
  message text not null
    check (char_length(message) between 5 and 2000),
  created_at timestamptz not null default now()
);

create index if not exists beta_feedback_user_created_idx
  on public.beta_feedback (user_id, created_at desc);

alter table public.beta_feedback enable row level security;

revoke all on table public.beta_feedback from anon, authenticated;
grant select, insert on table public.beta_feedback to authenticated;

drop policy if exists "beta_feedback_select_own" on public.beta_feedback;
create policy "beta_feedback_select_own"
  on public.beta_feedback for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "beta_feedback_insert_own" on public.beta_feedback;
create policy "beta_feedback_insert_own"
  on public.beta_feedback for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

create table if not exists public.product_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_name text not null
    check (char_length(event_name) between 1 and 80),
  scan_id uuid references public.comic_scans(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists product_events_user_created_idx
  on public.product_events (user_id, created_at desc);

create index if not exists product_events_event_created_idx
  on public.product_events (event_name, created_at desc);

create index if not exists product_events_scan_id_idx
  on public.product_events (scan_id)
  where scan_id is not null;

alter table public.product_events enable row level security;

revoke all on table public.product_events from anon, authenticated;
grant insert on table public.product_events to authenticated;
grant usage, select on sequence public.product_events_id_seq to authenticated;

drop policy if exists "product_events_insert_own" on public.product_events;
create policy "product_events_insert_own"
  on public.product_events for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

commit;
